public without sharing class OrderHelper {
    /**
     * @name AfterUpdate
     * @description
     * @param List<Order> newList
     * @param List<Order> oldList
     * @return void
    **/
    public static void AfterUpdate(List<Order> newList, List<Order> oldList){
        Set<Id> orderIds = new Set<Id>();
        for (Integer i = 0; i < newList.size(); i++){
            if (newList[i].Status == Constants.ACTIVATED_ORDER_STATUS && oldList[i].Status == Constants.DRAFT_ORDER_STATUS){
                orderIds.add(newList[i].Id);
            }
        }
        if(orderIds.size() > 0){
            RollUpOrderItems(orderIds);
        }
    }

    /**
     * @name RollUpOrderItems
     * @description Given a set of Activated Order ids, query the child Order Items and related Products to calculate Inventory levels
     * @param Set<Id> activatedOrderIds
     * @return void
    **/
    public static void RollUpOrderItems(Set<Id> activatedOrderIds){
        //ToDo: Declare a Map named "productMap" of Ids to Product2 records
        Map<Id, Product2> productMap = new Map<Id, Product2>();
        //ToDo: Loop through a query of OrderItems related to the activatedOrderIds
        Set<Id> productIds = new Set<Id>();
        for (OrderItem oi : [SELECT Id, Product2Id, Quantity FROM OrderItem WHERE OrderId IN :activatedOrderIds] ){
            if(!productIds.contains(oi.Product2Id)){
                productIds.add(oi.Product2Id);
            }
        }
        //ToDo: Populate the map with the Id of the related Product2 as the key and Product2 record as the value
        for (Product2 prod : [SELECT Id FROM Product2 WHERE Id IN :productIds] ){
            productMap.put(prod.Id, prod);
        }
        //ToDo: Loop through a query that aggregates the OrderItems related to the Products in the ProductMap keyset
        List<AggregateResult> ars = [SELECT Product2Id, SUM(Quantity) totalQuantity FROM OrderItem WHERE Product2Id IN :productMap.keySet() GROUP BY Product2Id];
        //ToDo: Perform an update on the records in the productMap
        List<Product2> productsToUpdate = new List<Product2>();
        for (AggregateResult ar : ars){
            Product2 prod = productMap.get((Id)ar.get('Product2Id'));
            prod.Quantity_Ordered__c = (Decimal)ar.get('totalQuantity');
            productsToUpdate.add(prod);
        }
        try {
            update productsToUpdate;
            System.debug('Products updated: ' + productsToUpdate);
        } catch(DmlException e) {
            System.debug('The following exception has occurred: ' + e.getMessage());
        }
    }

}