name: PR Check

on: [push] # プルリクエスト作成時に実行

jobs:
  Hello: # 1つ目のジョブ
    name: Say Hello
    runs-on: ubuntu-latest
    steps:
      - name: Run say hello
        run: echo "Say hellooo..." # 実際には必要なスクリプトやコマンドを記述
