name: PR Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  Hello:
    name: Say Hello
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v3
      - name: "Install Salesforce CLI"
        run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
          mkdir ~/sfdx
          tar xJf sfdx-linux-x64.tar.xz -C ~/sfdx --strip-components 1
          echo "$HOME/sfdx/bin" >> $GITHUB_PATH
          ~/sfdx/bin/sfdx version
      - name: Echo PR Title
        run: echo ${{ github.event.pull_request.title }}
      - name: Authenticate to Salesforce
        run: sf org login web --client-id 3MVG9bZIBBVRES4FWxUUu9Kr03DKn8fvX4ED6MYzm5QEIc80r5fL6oFSFbq9StEcefQONElQvDA8U2sokPNuQ --set-default-dev-hub --alias aasenv
      - name: Run Apex Tests
        run: sf apex run test --target-org aasenv --class-names ConstantsTest --synchronous
