name: PR Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  Hello:
    name: Say Hello
    runs-on: ubuntu-latest
    steps:
      - name: Run say hello
        run: PR_BODY="${{ github.event.pull_request.body || 'No body provided' }}"
        echo "PR Body: $PR_BODY"
